[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "src"
version = "0.0.1"
authors = [
    { name = "Kartik Shivakumar Gadad", email = "kartikshivakumargadad@gmail.com" },
]
description = "MLOps project package"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
include = ["src*"]
